FROM maven:3.8.1-jdk-11-slim AS maven
COPY ./pom.xml ./pom.xml
COPY ./src ./src
RUN mvn dependency:go-offline -B
RUN mvn package
FROM openjdk:11-jre-slim
WORKDIR /appdir
COPY --from=maven target/ecs-server.jar ./appdir/ecs-server.jar
ENTRYPOINT ["java", "-jar", "./appdir/ecs-server.jar"]