FROM maven:3.8.1-jdk-11-slim AS maven
EXPOSE 3000
EXPOSE 4000
COPY ./pom.xml ./pom.xml
COPY ./src ./src
RUN mvn dependency:go-offline -B
RUN mvn package
FROM openjdk:11-jre-slim
WORKDIR /appdir
COPY --from=maven target/kv-server.jar ./appdir/kv-server.jar
ENTRYPOINT ["java", "-jar", "./appdir/kv-server.jar"]